## Alpine: ~10MB, basic+zsh+cbuild+ureka-cpp Dependencies: ~277MB (Mac-arm64), ~412MB (Windows-amd64)
FROM alpine:3.20

## Required packages (also, Combining Commands to Save Space)
RUN apk update \
    && apk add \
    vim \
    tree \
    ## C Build
    build-base \
    # gcc \
    # g++ \
    # make \
    ## <Optional> CMake (for self-built GoogleTest)
    # cmake \
    ## <Optional> Python (for testing self-built mbedtls)
    # python3 \
    ## <Optional> Zsh & Oh-My-Zsh
    zsh \
    zsh-vcs \
    curl \
    git \
    ## <Dependencies> Ureka-Cpp
    nlohmann-json \
    mbedtls2-dev \ 
    gtest-dev

## Working Directory
WORKDIR /root

## <Optional> Oh-My-Zsh (& Configuration)
RUN sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
COPY ./installed/zshrc /root/.zshrc

## <Dependencies (Self-build)> Ureka-Cpp: nlohmann-json, mbedtls, gtest
##      <Warning> It will simply replace entire system local path. 
##                If you want to install other packages in system local path, do further management.
# COPY ./installed/alpine_mac/prebuilt_nlohmann_mbedtls_and_gtest_lib /usr/local

## CMD
CMD [ "zsh" ]
