## Totally: ~601MB (Mac-arm64), ~854MB (Windows-amd64)
FROM ubuntu:24.04

## Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive


## Required packages (also, Combining Commands to Save Space)
RUN apt update \
    && apt install -y \
    ## Sometimes Error-prone: --no-install-recommends
    # && apt install -y --no-install-recommends \
    # Basic
    vim \
    tree \
    ## C Build
    # gcc \
    # g++ \
    # make \
    ## <Optional> CMake (for self-built GoogleTest)
    # cmake \
    build-essential


## Working Directory
WORKDIR /root


## <Optional> Zsh & Oh-My-Zsh
RUN apt update \
    && apt install -y \
    zsh \
    fonts-powerline \
    curl \
    git

## <Optional> Oh-My-Zsh (& Configuration)
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
COPY ./installed/zshrc /root/.zshrc

## <Optional> Set Zsh as default shell
# RUN chsh -s $(which zsh)


## <Dependencies> Ureka-Cpp
RUN apt update \
    && apt install -y \
    ## <Optional> Python (for testing self-built mbedtls)
    # python3 \
    nlohmann-json3-dev \
    libmbedtls-dev \
    libgtest-dev


## <Dependencies (Self-build)> Ureka-Cpp: nlohmann-json, mbedtls, gtest
##      <Warning> It will simply replace entire system local path. 
##                If you want to install other packages in system local path, do further management.
# COPY ./installed/ubuntu_mac/prebuilt_nlohmann_mbedtls_and_gtest_lib /usr/local


## CMD
# CMD [ "sh" ]
CMD [ "zsh" ]
