## Totally: ~292MB (Mac-arm64), ~422MB (Windows-amd64)
FROM alpine:3.20

## Required packages (also, Combining Commands to Save Space)
RUN apk update \
    && apk add \
    # Basic
    vim \
    tree \
    ## C Build
    # gcc \
    # g++ \
    # make \
    ## <Optional> CMake (for self-built GoogleTest)
    # cmake \
    build-base


## Working Directory
WORKDIR /root


## <Optional> Zsh & Oh-My-Zsh
RUN apk update \
    && apk add \    
    zsh \
    zsh-vcs \
    curl \
    git 

## <Optional> Oh-My-Zsh (& Configuration)
RUN sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
COPY ./installed/zshrc /root/.zshrc


## <Dependencies> Ureka-Cpp
RUN apk update \
    && apk add \ 
    ## <Optional> Python (for testing self-built mbedtls)
    # python3 \
    nlohmann-json \
    mbedtls2-dev \ 
    gtest-dev

## <Dependencies (Self-build)> Ureka-Cpp: nlohmann-json, mbedtls, gtest
##      <Warning> It will simply replace entire system local path. 
##                If you want to install other packages in system local path, do further management.
# COPY ./installed/alpine_mac/prebuilt_nlohmann_mbedtls_and_gtest_lib /usr/local


## CMD
# CMD [ "sh" ]
CMD [ "zsh" ]
